name: create_vm 
on:
  workflow_dispatch:
    inputs:
      domain_name:
        type: string
        required: true 
      folder_name:
        type: string
        required: true 
      ssl_enabled:
        type: string
        required: true 
  workflow_call:
    inputs:
      domain_name:
        type: string
        required: true
      folder_name:
        type: string
        required: true
permissions:
  id-token: write
  contents: read
jobs:
  create_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.47.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/create_vm.sh
            $GITHUB_WORKSPACE/create_vm2.sh ${{ inputs.domain_name }} ${{ inputs.folder_name }} ${{ inputs.ssl_enabled }}
