name: create_vm 
on:
  workflow_dispatch:
    inputs:
      domain_name:
        type: string
        required: true 
      folder_name:
        type: string
        required: true 
      ssl_enabled:
        type: string
        required: true 
  workflow_call:
    inputs:
      domain_name:
        type: string
        required: true
      folder_name:
        type: string
        required: true

jobs:
  create_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



